/**
 * Comprehensive audit action types for regulatory compliance.
 * Covers all sensitive operations across the platform.
 */
export enum AuditActionType {
  // Policy Lifecycle
  POLICY_CREATED = 'POLICY_CREATED',
  POLICY_RENEWED = 'POLICY_RENEWED',
  POLICY_CANCELLED = 'POLICY_CANCELLED',
  POLICY_EXPIRED = 'POLICY_EXPIRED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  POLICY_VIEWED = 'POLICY_VIEWED',
  POLICY_EXPORTED = 'POLICY_EXPORTED',

  // Claims Management
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_REJECTED = 'CLAIM_REJECTED',
  CLAIM_SETTLED = 'CLAIM_SETTLED',
  CLAIM_UPDATED = 'CLAIM_UPDATED',
  CLAIM_VIEWED = 'CLAIM_VIEWED',
  CLAIM_EXPORTED = 'CLAIM_EXPORTED',
  CLAIM_DOCUMENT_ADDED = 'CLAIM_DOCUMENT_ADDED',
  CLAIM_DOCUMENT_REMOVED = 'CLAIM_DOCUMENT_REMOVED',

  // DAO Governance
  PROPOSAL_SUBMITTED = 'PROPOSAL_SUBMITTED',
  PROPOSAL_FINALIZED = 'PROPOSAL_FINALIZED',
  PROPOSAL_CANCELLED = 'PROPOSAL_CANCELLED',
  PROPOSAL_EXECUTED = 'PROPOSAL_EXECUTED',
  PROPOSAL_VIEWED = 'PROPOSAL_VIEWED',
  VOTE_CAST = 'VOTE_CAST',
  VOTE_RETRACTED = 'VOTE_RETRACTED',

  // User Management
  USER_REGISTERED = 'USER_REGISTERED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_VIEWED = 'USER_VIEWED',
  USER_EXPORTED = 'USER_EXPORTED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_PERMISSION_GRANTED = 'USER_PERMISSION_GRANTED',
  USER_PERMISSION_REVOKED = 'USER_PERMISSION_REVOKED',

  // Authentication & Authorization
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  MFA_CHALLENGE_INITIATED = 'MFA_CHALLENGE_INITIATED',
  MFA_CHALLENGE_PASSED = 'MFA_CHALLENGE_PASSED',
  MFA_CHALLENGE_FAILED = 'MFA_CHALLENGE_FAILED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_TERMINATED = 'SESSION_TERMINATED',

  // Payments & Financial
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  PAYOUT_INITIATED = 'PAYOUT_INITIATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  WALLET_LINKED = 'WALLET_LINKED',
  WALLET_UNLINKED = 'WALLET_UNLINKED',

  // File Operations
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_VIEWED = 'FILE_VIEWED',

  // Oracle & Data
  ORACLE_DATA_REQUESTED = 'ORACLE_DATA_REQUESTED',
  ORACLE_DATA_RECEIVED = 'ORACLE_DATA_RECEIVED',
  ORACLE_DATA_VERIFIED = 'ORACLE_DATA_VERIFIED',

  // Fraud Detection
  FRAUD_ALERT_TRIGGERED = 'FRAUD_ALERT_TRIGGERED',
  FRAUD_ALERT_RESOLVED = 'FRAUD_ALERT_RESOLVED',
  FRAUD_RULE_CREATED = 'FRAUD_RULE_CREATED',
  FRAUD_RULE_UPDATED = 'FRAUD_RULE_UPDATED',
  FRAUD_RULE_DELETED = 'FRAUD_RULE_DELETED',

  // Business Rules
  RULE_CREATED = 'RULE_CREATED',
  RULE_UPDATED = 'RULE_UPDATED',
  RULE_DELETED = 'RULE_DELETED',
  RULE_EXECUTED = 'RULE_EXECUTED',
  RULE_VERSION_CREATED = 'RULE_VERSION_CREATED',

  // Notifications
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  NOTIFICATION_PREFERENCES_UPDATED = 'NOTIFICATION_PREFERENCES_UPDATED',

  // Admin & System
  ADMIN_ACTION = 'ADMIN_ACTION',
  SYSTEM_CONFIG_CHANGED = 'SYSTEM_CONFIG_CHANGED',
  AUDIT_LOG_EXPORTED = 'AUDIT_LOG_EXPORTED',
  AUDIT_LOG_ARCHIVED = 'AUDIT_LOG_ARCHIVED',

  // Data Access & Privacy (GDPR)
  DATA_EXPORT_REQUESTED = 'DATA_EXPORT_REQUESTED',
  DATA_EXPORT_COMPLETED = 'DATA_EXPORT_COMPLETED',
  DATA_DELETION_REQUESTED = 'DATA_DELETION_REQUESTED',
  DATA_DELETION_COMPLETED = 'DATA_DELETION_COMPLETED',
  DATA_ACCESS_REQUESTED = 'DATA_ACCESS_REQUESTED',
  CONSENT_GIVEN = 'CONSENT_GIVEN',
  CONSENT_REVOKED = 'CONSENT_REVOKED',

  // API & Integration
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  WEBHOOK_REGISTERED = 'WEBHOOK_REGISTERED',
  WEBHOOK_REMOVED = 'WEBHOOK_REMOVED',
  INTEGRATION_CONNECTED = 'INTEGRATION_CONNECTED',
  INTEGRATION_DISCONNECTED = 'INTEGRATION_DISCONNECTED',
}